# Generated by Django 5.0.4 on 2024-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='children',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employmentYears',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='family',
            field=models.PositiveIntegerField(),
        ),
    ]
